### ISSUE TITLE
Compilation erros

### ISSUE THREAD

**Issue by lczech** [phylo42/EPIK#7]
Hi there,

when following the installation instructions, using `git clone` to obtain the latest version, I ran into compilation errors:

```
epik/i2l/include/i2l/seq.h:354:32: error: ‘runtime_error’ is not a member of ‘std’
```

and the same in `epik/i2l/include/i2l/phylo_tree.h:293`. Adding `#include <stdexcept>` to both headers fixes the issue.

Furthermore, I got the warning:

```
epik/i2l/include/i2l/seq.h:341:17: warning: control reaches end of non-void function [-Wreturn-type]
  341 |                 case '*':
```

Looking at the source, indeed, `key_to_code()` does not return a value for some values, which seems like a bug.

Also, I noticed that the default branch of the repo seems to be the dev branch, which might not be intended.

Cheers and so long
Lucas

**Comment by nromashchenko** [comment]
Hi Lucas!

Thanks for all issues created, the project definitely needs a critical independent look and a little more testing. Please don't hesitate to report every little detail you find important for the sake of code purity :)

> Also, I noticed that the default branch of the repo seems to be the dev branch, which might not be intended.

This was intended for some reasons. We will release a new version and will switch back to master.

cheers!
N

**Comment by lczech** [comment]
Hey hey,

> Please don't hesitate to report every little detail you find important for the sake of code purity :)

Will do ;-)

> This was intended for some reasons. We will release a new version and will switch back to master.

Hm, I don't get it, you can create release versions from any branch. The danger of having the dev branch as the default, and then stating in your README to use `git clone` on that is that users will end up with unfinished intermediate work... It might help to avoid that to either recommend to users to obtain release versions only, or have a stable master branch ;-)

Cheers
Lucas
