### ISSUE TITLE
Mention format for `--max-ram`

### ISSUE THREAD

**Issue by lczech** [phylo42/EPIK#9]
Hey @nromashchenko,

the new option `--max-ram` is a really useful improvement, thanks for implementing this! One short comment though: The readme does not state how to provide this. The [`dehumanize_ram`](https://github.com/phylo42/EPIK/commit/8f7d2f08f2c29ac6211a34f9df5dafdd590ddcaa#diff-b436e3a2a96af56a0d4110daa7375363e843586f3e5185ed7a775f6a8a5c9f67R133) function tells me that suffixes `[BKMG]` are supported, but that should be mentioned in the readme ;-)

Cheers
Lucas

PS: As for the "unfortunate naming" of that function, maybe call it `parse_cli_ram_value` or something like that ;-)

**Comment by nromashchenko** [comment]
Hi @lczech 

Thanks for noting this. Issue fixed by the [pull request](https://github.com/phylo42/EPIK/pull/11) and [this commit](https://github.com/phylo42/EPIK/commit/c8c7914a58a0a336548ab3161b835ead5d814fa2)

Cheers!
